steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ["build", 't', "gcr.io/misc-project-429205/node_app:v1", "."]

- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/misc-project-429205/node_app:v1"]


- name: "gcr.io/cloud-builders/gke-deploy"
  args: [
        "run", 
        "--filename=deployment.yaml", 
        "--image=gcr.io/misc-project-429205/node_app:v1", 
        "--location=us-west4", 
        "--cluster=my-first-cluster"
        ]

options:
  logging: CLOUD_LOGGING_ONLY