steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ["build", '-t', "gcr.io/my-first-project-429710/node_app:v5", "."]

- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/my-first-project-429710/node_app:v5"]


- name: "gcr.io/cloud-builders/gke-deploy"
  args: [
        "run", 
        "--filename=deployment.yaml", 
        "--image=gcr.io/my-first-project-429710/node_app:v5", 
        "--location=us-west4-a", 
        "--cluster=my-first-cluster"
        ]

options:
  logging: CLOUD_LOGGING_ONLY