apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-label
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - image: gcr.io/misc-project-429205/node_app:v2
        name: node-app-container
        env: 
          - name: GOOGLE_APPLICATION_CREDENTIALS
            valueFrom: 
              secretKeyRef:
                name: pods-secrets
                key: sapath.json
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-lb
  namespace: default
  # annotations:
  #   beta.cloud.google.com/backend-config: '{"default": "enable-iap"}'
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: node-app
  sessionAffinity: None
  type: LoadBalancer